Gestor/Controllers/TipoesController.cs
// Custo_3.PlanejVendas

using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Gestor.Models;
using X.PagedList;

namespace Gestor
{
    public class TipoesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Tipoes
        public ActionResult Index(int? page)
        {
            var model = db.Tipos
                        .OrderBy(t => t.Apelido);

            var pageNumber = page ?? 1;
            var onePageHistory = model.ToPagedList(pageNumber, Global.PageNumber);

            ViewBag.OnePageHistory = onePageHistory;

            return View();
        }

        // GET: Tipoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tipo tipo = db.Tipos.Find(id);
            if (tipo == null)
            {
                return HttpNotFound();
            }
            return View(tipo);
        }

        // GET: Tipoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tipoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TipoId,Apelido,Descricao")] Tipo tipo)
        {
            if (ModelState.IsValid)
            {
                db.Tipos.Add(tipo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tipo);
        }

        // GET: Tipoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tipo tipo = db.Tipos.Find(id);
            if (tipo == null)
            {
                return HttpNotFound();
            }
            return View(tipo);
        }

        // POST: Tipoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TipoId,Apelido,Descricao")] Tipo tipo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipo);
        }

        // GET: Tipoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tipo tipo = db.Tipos.Find(id);
            if (tipo == null)
            {
                return HttpNotFound();
            }
            return View(tipo);
        }

        // POST: Tipoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tipo tipo = db.Tipos.Find(id);
            return View("Erase", tipo);
        }

        // POST: Tipoes/Erase/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Erase(int id)
        {
            Tipo tipo = db.Tipos.Find(id);
            db.Tipos.Remove(tipo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Search(string search)
        {
            var model = db.Tipos
                .FirstOrDefault(g => g.Apelido.Contains(search));

            if (model == null)
            {
                DbLogger.Log(Reason.Info, $"Procura pelo Tipo {search} não produziu resultado");
                return Content($"Item {search} não encontrado");
            }

            return View("Details", model);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gestor/Views/Tipoes/Common.cshtml
@model Gestor.Models.Tipo

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Apelido)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Apelido)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Descricao)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Descricao)
    </dd>
</dl>

Gestor/Views/Tipoes/Create.cshtml
@model Gestor.Models.Tipo

@{
    ViewBag.Title = "Criar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Criar</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tipo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Apelido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apelido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apelido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input class="btn btn-sm" type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar a lista", "Index")
</div>

Gestor/Views/Tipoes/Delete.cshtml
@model Gestor.Models.Tipo

@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar</h2>

<h3>Tem certeza que deseja eliminar o registro?</h3>
<div>
    <h4>Tipo</h4>
    <hr />

    @Html.Partial("Common")

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input class="btn btn-sm" type="submit" value="Eliminar" class="btn btn-primary" /> |
            @Html.ActionLink("Retronar a lista", "Index")
        </div>
    }
</div>

Gestor/Views/Tipoes/Details.cshtml
@model Gestor.Models.Tipo

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes</h2>

<div>
    <h4>Tipo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Apelido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apelido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Alterar", "Edit", new { id = Model.TipoId }) |
    @Html.ActionLink("Retornar a lista", "Index")
</p>

Gestor/Views/Tipoes/Edit.cshtml
@model Gestor.Models.Tipo

@{
    ViewBag.Title = "Alterar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Alterar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tipo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TipoId)

        <div class="form-group">
            @Html.LabelFor(model => model.Apelido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apelido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apelido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input class="btn btn-sm" type="submit" value="Gravar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar a lista", "Index")
</div>

Gestor/Views/Tipoes/Erase.cshtml
@model Gestor.Models.Tipo

@{
    ViewBag.Title = "Confirmar Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Confirmar Eliminar</h2>
<h3>CONFIRME que realmente deseja eliminar o registro?</h3>
@Html.Partial("Common")
@using (Html.BeginForm("Erase", "Tipoes", new { Id = Model.TipoId }))
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input class="btn btn-sm" type="submit" value="Eliminar" class="btn btn-primary" /> |
        @Html.ActionLink("Retornar a lista sem eliminar", "Index")
    </div>
}

Gestor/Views/Tipoes/Index.cshtml
@model IEnumerable<Gestor.Models.Tipo>
@using X.PagedList.Mvc;
@using X.PagedList;
@{
    ViewBag.Title = "Índice";
    Layout = "~/Views/Shared/_Layout.cshtml";
    IPagedList<Gestor.Models.Tipo> tipos = ViewBag.OnePageHistory;
}
<h2>Índice</h2>
<p>
    @Html.ActionLink("Criar novo tipo", "Create")
</p>
@using (Html.BeginForm("Search", "Tipoes", FormMethod.Post))
{
    <p>
        Tipo: @Html.TextBox("search")
        <input class="btn btn-sm" type="submit" value="Procurar" />
    </p>
}
<div class="height600">
    <table class="table fancyTable">
        <thead>
            <tr>
                <th></th>
                <th>
                    @Html.DisplayNameFor(model => model.Apelido)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Descricao)
                </th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in tipos)
            {
                <tr>
                    <td>
                        @Html.ActionLink("Alterar", "Edit", new { id = item.TipoId }) <br />
                        @Html.ActionLink("Detalhes", "Details", new { id = item.TipoId }) <br />
                        @Html.ActionLink("Elminar", "Delete", new { id = item.TipoId })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Apelido)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descricao)
                    </td>
                    <td>
                        @Html.ActionLink("Alterar", "Edit", new { id = item.TipoId }) <br />
                        @Html.ActionLink("Detalhes", "Details", new { id = item.TipoId }) <br />
                        @Html.ActionLink("Elminar", "Delete", new { id = item.TipoId })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@Html.PagedListPager((IPagedList)ViewBag.OnePageHistory, page => Url.Action("Index", new { page }))

@section scripts {
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery.fixedheadertable.min.js"></script>

    <script type="text/javascript">

        $('.table').fixedHeaderTable({
            footer: true,
            cloneHeadToFoot: false,
            altClass: 'odd',
            autoShow: true
        });

    </script>

}