Gestor/Models/Area.cs
using System.ComponentModel.DataAnnotations;

namespace Gestor.Models
{
    public class Area
    {
        public int AreaId { get; set; }

        [StringLength(2)]
        [Display(Name = "Código")]
        public string Apelido { get; set; }

        [StringLength(16)]
        [Display(Name = "Área")]
        public string Nome { get; set; }
    }
}

Gestor/Controllers/AreasController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Gestor.Models;
using X.PagedList;

namespace Gestor.Controllers
{
    public class AreasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Areas
        public ActionResult Index(int? page)
        {
            var areas = db.Areas.OrderBy(a => a.Apelido);

            var pageNumber = page ?? 1;
            var onePageHistory = areas.ToPagedList(pageNumber, Global.PageNumber);

            ViewBag.OnePageHistory = onePageHistory;

            return View();
        }

        // GET: Areas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Area area = db.Areas.Find(id);
            if (area == null)
            {
                return HttpNotFound();
            }
            return View(area);
        }

        // GET: Areas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Areas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AreaId,Apelido,Nome")] Area area)
        {
            if (ModelState.IsValid)
            {
                db.Areas.Add(area);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(area);
        }

        // GET: Areas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Area area = db.Areas.Find(id);
            if (area == null)
            {
                return HttpNotFound();
            }
            return View(area);
        }

        // POST: Areas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AreaId,Apelido,Nome")] Area area)
        {
            if (ModelState.IsValid)
            {
                db.Entry(area).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(area);
        }

        // GET: Areas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Area area = db.Areas.Find(id);
            if (area == null)
            {
                return HttpNotFound();
            }
            return View(area);
        }

        // POST: Estruturas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Area area = db.Areas.Find(id);
            return View("Erase", area);
        }

        // POST: Estruturas/Erase/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Erase(int id)
        {
            Area area = db.Areas.Find(id);
            db.Areas.Remove(area);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Search(string search)
        {
            var model = db.Areas
                .SingleOrDefault(g => g.Apelido == search);

            if (model == null)
            {
                DbLogger.Log(Reason.Info, $"Procura pela Área {search} não produziu resultado");
                return Content($"Item {search} não encontrado");
            }

            return View("Details", model);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gestor/Views/Areas/Common.cshtml
@model Gestor.Models.Area

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Apelido)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Apelido)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Nome)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Nome)
    </dd>
</dl>

Gestor/Views/Areas/Create.cshtml
@model Gestor.Models.Area

@{
    ViewBag.Title = "Criar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Criar</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Área</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Apelido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apelido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apelido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input class="btn btn-sm" type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar a lista", "Index")
</div>

Gestor/Views/Areas/Delete.cshtml
@model Gestor.Models.Area

@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar</h2>

<h3>Tem certeza que deseja eliminar o registro?</h3>
<div>
    <h4>Área</h4>
    <hr />

    @Html.Partial("Common")

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input class="btn btn-sm" type="submit" value="Eliminar" class="btn btn-primary" /> |
            @Html.ActionLink("Retornar a lista", "Index")
        </div>
    }
</div>

Gestor/Views/Areas/Details.cshtml
@model Gestor.Models.Area

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes</h2>

<div>
    <h4>Área</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Apelido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apelido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Alterar", "Edit", new { id = Model.AreaId }) |
    @Html.ActionLink("Retornar a lista", "Index")
</p>

Gestor/Views/Areas/Edit.cshtml
@model Gestor.Models.Area

@{
    ViewBag.Title = "Alterar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Alterar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Área</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AreaId)

        <div class="form-group">
            @Html.LabelFor(model => model.Apelido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apelido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apelido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input class="btn btn-sm" type="submit" value="Gravar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar a lista", "Index")
</div>

Gestor/Views/Areas/Erase.cshtml
@model Gestor.Models.Area
@{
    ViewBag.Title = "Confirmar Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Confirmar Eliminar</h2>
<h3>CONFIRME que realmente deseja eliminar o registro?</h3>
@Html.Partial("Common")
@using (Html.BeginForm("Erase", "Areas", new { Id = Model.AreaId }))
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input class="btn btn-sm" type="submit" value="Eliminar" class="btn btn-primary" /> |
        @Html.ActionLink("Retornar a lista sem eliminar", "Index")
    </div>
}

Gestor/Views/Areas/Index.cshtml
@model IEnumerable<Gestor.Models.Area>
@using X.PagedList.Mvc;
@using X.PagedList;
@{
    ViewBag.Title = "Índice";
    Layout = "~/Views/Shared/_Layout.cshtml";
    IPagedList<Gestor.Models.Area> areas = ViewBag.OnePageHistory;
}
<h2>Índice</h2>
@using (Html.BeginForm("Search", "Areas", FormMethod.Post))
{
    <p>
        Código: @Html.TextBox("search")
        <input class="btn btn-sm" type="submit" value="Procurar" />
    </p>
}
<p>
    @Html.ActionLink("Criar nova área", "Create")
</p>
<div class="height600">
    <table class="table fancyTable">
        <thead>
            <tr>
                <th></th>
                <th>
                    @Html.DisplayNameFor(model => model.Apelido)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in areas)
            {
                <tr>
                    <td>
                        @Html.ActionLink("Alterar", "Edit", new { id = item.AreaId }) <br />
                        @Html.ActionLink("Detalhes", "Details", new { id = item.AreaId }) <br />
                        @Html.ActionLink("Eliminar", "Delete", new { id = item.AreaId })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Apelido)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.ActionLink("Alterar", "Edit", new { id = item.AreaId }) <br />
                        @Html.ActionLink("Detalhes", "Details", new { id = item.AreaId }) <br />
                        @Html.ActionLink("Eliminar", "Delete", new { id = item.AreaId })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@Html.PagedListPager((IPagedList)ViewBag.OnePageHistory, page => Url.Action("Index", new { page }))

@section scripts {
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery.fixedheadertable.min.js"></script>

    <script type="text/javascript">

        $('.table').fixedHeaderTable({
            footer: true,
            cloneHeadToFoot: false,
            altClass: 'odd',
            autoShow: true
        });

    </script>

}