Gestor/Controllers/CustoCargoDiretoesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Gestor.Models;
using X.PagedList;

namespace Gestor.Controllers
{
    [RoutePrefix("CustoCargos")]
    public class CustoCargoDiretoesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CustoCargoDiretoes
        [Route]
        public ActionResult Index(int? page)
        {
            var custoCargoDiretos = db.CustoCargoDiretos
                .Include(c => c.Setor)
                .OrderBy(c => c.Setor.Codigo);

            var pageNumber = page ?? 1;
            var onePageHistory = custoCargoDiretos.ToPagedList(pageNumber, Global.PageNumber);

            ViewBag.OnePageHistory = onePageHistory;

            return View();
        }

        // GET: CustoCargoDiretoes/Details/5
        [Route("Details")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustoCargoDireto custoCargoDireto = db.CustoCargoDiretos
                .Include(c => c.Setor)
                .SingleOrDefault(c => c.Id == id);

            if (custoCargoDireto == null)
            {
                return HttpNotFound();
            }
            return View(custoCargoDireto);
        }

        // GET: CustoCargoDiretoes/Create
        public ActionResult Create()
        {
            ViewBag.SetorId = new SelectList(db.Setores, "SetorId", "Codigo");
            return View();
        }

        // POST: CustoCargoDiretoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SetorId,Operadores,MoDireta,CodigoLiderApoio,MoDiretaLiderApoio,HorasModOperadores,HorasModTotal,CustoUnitario,RateioSetor20,RateioSetor40,RateioSetor50,RateioSetor60,SomaIndiretos,SomaDiretoIndireto,RateioCustoUnitario")] CustoCargoDireto custoCargoDireto)
        {
            if (ModelState.IsValid)
            {
                db.CustoCargoDiretos.Add(custoCargoDireto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SetorId = new SelectList(db.Setores, "SetorId", "Codigo", custoCargoDireto.SetorId);
            return View(custoCargoDireto);
        }

        // GET: CustoCargoDiretoes/Edit/5
        [Route("Edit")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustoCargoDireto custoCargoDireto = db.CustoCargoDiretos.Find(id);
            if (custoCargoDireto == null)
            {
                return HttpNotFound();
            }
            ViewBag.SetorId = new SelectList(db.Setores, "SetorId", "Codigo", custoCargoDireto.SetorId);
            return View(custoCargoDireto);
        }

        // POST: CustoCargoDiretoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Route("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SetorId,Operadores,MoDireta,CodigoLiderApoio,MoDiretaLiderApoio,HorasModOperadores,HorasModTotal,CustoUnitario,RateioSetor20,RateioSetor40,RateioSetor50,RateioSetor60,SomaIndiretos,SomaDiretoIndireto,RateioCustoUnitario")] CustoCargoDireto custoCargoDireto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(custoCargoDireto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SetorId = new SelectList(db.Setores, "SetorId", "Codigo", custoCargoDireto.SetorId);
            return View(custoCargoDireto);
        }

        // GET: CustoCargoDiretoes/Delete/5
        [Route("Delete")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            CustoCargoDireto custoCargoDireto = db.CustoCargoDiretos
                .Include(c => c.Setor)
                .SingleOrDefault(c => c.Id == id);

            if (custoCargoDireto == null)
            {
                return HttpNotFound();
            }
            return View(custoCargoDireto);
        }

        // POST: CustoCargoDiretoes/Delete/5
        [Route("Delete")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CustoCargoDireto custoCargoDireto = db.CustoCargoDiretos
                .Include(c => c.Setor)
                .SingleOrDefault(c => c.Id == id);

            return View("Erase", custoCargoDireto);
        }

        // POST: CustoCargoDiretoes/Erase/5
        [HttpPost]
        [Route("Erase")]
        [ValidateAntiForgeryToken]
        public ActionResult Erase(int id)
        {
            CustoCargoDireto custoCargoDireto = db.CustoCargoDiretos.Find(id);
            db.CustoCargoDiretos.Remove(custoCargoDireto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Route("Search")]
        [HttpPost]
        public ActionResult Search(string search)
        {
            var model = db.CustoCargoDiretos
                .Include(c => c.Setor)
                .SingleOrDefault(g => g.Setor.Codigo == search);

            if (model == null)
            {
                DbLogger.Log(Reason.Info, $"Procura pelo Custo Cargo {search} não produziu resultado");
                return Content($"Item {search} não encontrado");
            }

            return View("Details", model);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gestor/Views/CustoCargoDiretoes/Common.cshtml
@model Gestor.Models.CustoCargoDireto

<dl class="dl-horizontal">

    <dt>
        Setor de Produção
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Setor.Descricao)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Setor.Codigo)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Setor.Codigo)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Operadores)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Operadores)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.MoDireta)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.MoDireta)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.CodigoLiderApoio)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.CodigoLiderApoio)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.MoDiretaLiderApoio)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.MoDiretaLiderApoio)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.HorasModOperadores)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.HorasModOperadores)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.HorasModTotal)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.HorasModTotal)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.CustoUnitario)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.CustoUnitario)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.RateioSetor20)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.RateioSetor20)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.RateioSetor40)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.RateioSetor40)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.RateioSetor50)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.RateioSetor50)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.RateioSetor60)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.RateioSetor60)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.SomaIndiretos)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.SomaIndiretos)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.SomaDiretoIndireto)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.SomaDiretoIndireto)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.RateioCustoUnitario)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.RateioCustoUnitario)
    </dd>
</dl>

Gestor/Views/CustoCargoDiretoes/Create.cshtml
@model Gestor.Models.CustoCargoDireto

@{
    ViewBag.Title = "Criar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Criar</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Custo Cargo Direto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SetorId, "Setor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SetorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SetorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Operadores, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Operadores, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Operadores, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoDireta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoDireta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoDireta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodigoLiderApoio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodigoLiderApoio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodigoLiderApoio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoDiretaLiderApoio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoDiretaLiderApoio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoDiretaLiderApoio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HorasModOperadores, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HorasModOperadores, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HorasModOperadores, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HorasModTotal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HorasModTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HorasModTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustoUnitario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustoUnitario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustoUnitario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RateioSetor20, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RateioSetor20, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RateioSetor20, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RateioSetor40, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RateioSetor40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RateioSetor40, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RateioSetor50, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RateioSetor50, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RateioSetor50, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RateioSetor60, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RateioSetor60, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RateioSetor60, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SomaIndiretos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SomaIndiretos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SomaIndiretos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SomaDiretoIndireto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SomaDiretoIndireto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SomaDiretoIndireto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RateioCustoUnitario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RateioCustoUnitario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RateioCustoUnitario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input class="btn btn-sm" type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar a lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Gestor/Views/CustoCargoDiretoes/Delete.cshtml
@model Gestor.Models.CustoCargoDireto

@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar</h2>

<h3>Tem certeza que deseja eliminar o registro?</h3>
<div>
    <h4>Custo Cargo Direto</h4>
    <hr />

    @Html.Partial("Common")

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input class="btn btn-sm" type="submit" value="Eliminar" class="btn btn-primary" /> |
            @Html.ActionLink("Retornar a lista", "Index")
        </div>
    }
</div>

Gestor/Views/CustoCargoDiretoes/Details.cshtml
@model Gestor.Models.CustoCargoDireto

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes</h2>

<div>
    <h4>Custo Cargo Direto</h4>
    <hr />
    <dl class="dl-horizontal">
        
        <dt>
            Setor de Produção
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Setor.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Setor.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Setor.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Operadores)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Operadores)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoDireta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoDireta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CodigoLiderApoio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CodigoLiderApoio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoDiretaLiderApoio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoDiretaLiderApoio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HorasModOperadores)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HorasModOperadores)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HorasModTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HorasModTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustoUnitario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustoUnitario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RateioSetor20)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RateioSetor20)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RateioSetor40)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RateioSetor40)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RateioSetor50)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RateioSetor50)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RateioSetor60)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RateioSetor60)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SomaIndiretos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SomaIndiretos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SomaDiretoIndireto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SomaDiretoIndireto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RateioCustoUnitario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RateioCustoUnitario)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Alterar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Retornar a lista", "Index")
</p>

Gestor/Views/CustoCargoDiretoes/Edit.cshtml
@model Gestor.Models.CustoCargoDireto

@{
    ViewBag.Title = "Alterar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Alterar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Custo Cargo Direto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.SetorId, "Setor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SetorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SetorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Operadores, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Operadores, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Operadores, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoDireta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoDireta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoDireta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CodigoLiderApoio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodigoLiderApoio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodigoLiderApoio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MoDiretaLiderApoio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MoDiretaLiderApoio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoDiretaLiderApoio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HorasModOperadores, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HorasModOperadores, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HorasModOperadores, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HorasModTotal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HorasModTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HorasModTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustoUnitario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustoUnitario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustoUnitario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RateioSetor20, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RateioSetor20, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RateioSetor20, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RateioSetor40, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RateioSetor40, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RateioSetor40, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RateioSetor50, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RateioSetor50, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RateioSetor50, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RateioSetor60, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RateioSetor60, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RateioSetor60, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SomaIndiretos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SomaIndiretos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SomaIndiretos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SomaDiretoIndireto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SomaDiretoIndireto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SomaDiretoIndireto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RateioCustoUnitario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RateioCustoUnitario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RateioCustoUnitario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input class="btn btn-sm" type="submit" value="Gravar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar a lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Gestor/Views/CustoCargoDiretoes/Erase.cshtml
@model Gestor.Models.CustoCargoDireto
@{
    ViewBag.Title = "Confirmar Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Confirmar Eliminar</h2>
<h3>CONFIRME que realmente deseja eliminar o registro?</h3>
@Html.Partial("Common")
@using (Html.BeginForm("Erase", "CustoCargoDiretoes", new { Id = Model.Id }))
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input class="btn btn-sm" type="submit" value="Eliminar" class="btn btn-primary" /> |
        @Html.ActionLink("Retornar a lista sem eliminar", "Index")
    </div>
}