Gestor/Models/Categoria.cs
using System.ComponentModel.DataAnnotations;

namespace Gestor.Models
{
    public class Categoria
    {
        public int CategoriaId { get; set; }

        [StringLength(2)]
        [Display(Name = "Categoria")]
        public string Apelido { get; set; }

        [StringLength(50)]
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }
    }
}

Gestor/Controllers/CategoriasController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using X.PagedList;

namespace Gestor.Models
{
    public class CategoriasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Categorias
        public ActionResult Index(int? page)
        {
            var model = db.Categorias
                .OrderBy(c => c.Apelido);

            var pageNumber = page ?? 1;
            var onePageHistory = model.ToPagedList(pageNumber, Global.PageNumber);

            ViewBag.OnePageHistory = onePageHistory;

            return View();
        }

        // GET: Categorias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categoria categoria = db.Categorias.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // GET: Categorias/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categorias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoriaId,Apelido,Descricao")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                db.Categorias.Add(categoria);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categoria);
        }

        // GET: Categorias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categoria categoria = db.Categorias.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // POST: Categorias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoriaId,Apelido,Descricao")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categoria).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categoria);
        }

        // GET: Categorias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categoria categoria = db.Categorias.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // POST: Categorias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Categoria categoria = db.Categorias.Find(id);
            return View("Erase", categoria);
        }

        // POST: Categorias/Erase/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Erase(int id)
        {
            try
            {
                Categoria categoria = db.Categorias.Find(id);
                db.Categorias.Remove(categoria);
                db.SaveChanges();
                
            }
            catch (System.Data.Entity.Infrastructure.DbUpdateException)
            {
                DbLogger.Log(Reason.Info, $"Tentativa de eliminar Categoria id {id} existindo PlanejProducao associado");
                return Content("Não é possível eliminar pois existe um PlanejProducao associado a essa Categoria.");
            }

            catch (Exception ex)
            {
                DbLogger.Log(Reason.Error, $"Erro ao tentar eliminar Categoria Id {id}: {ex}");
                return Content("Categoria não eliminada devido a erro. Tente novamente ou notifique suporte.");
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Search(string search)
        {
            var graxa = db.Categorias
                .SingleOrDefault(g => g.Apelido == search);

            if (graxa == null)
            {
                DbLogger.Log(Reason.Info, $"Procura pela categoria {search} não produziu resultado");
                return Content($"Item {search} não encontrado");
            }

            return View("Details", graxa);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gestor/Views/Categorias/Common.cshtml
@model Gestor.Models.Categoria

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Apelido)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Apelido)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Descricao)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Descricao)
    </dd>
</dl>

Gestor/Views/Categorias/Create.cshtml
@model Gestor.Models.Categoria

@{
    ViewBag.Title = "Criar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Criar</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Categoria</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Apelido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apelido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apelido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input class="btn btn-sm" type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar a lista", "Index")
</div>

Gestor/Views/Categorias/Delete.cshtml
@model Gestor.Models.Categoria

@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar</h2>

<h3>Tem certeza que deseja eliminar o registro?</h3>
<div>
    <h4>Categoria</h4>
    <hr />

    @Html.Partial("Common")

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input class="btn btn-sm" type="submit" value="Eliminar" class="btn btn-primary" /> |
            @Html.ActionLink("Retornar a lista", "Index")
        </div>
    }
</div>

Gestor/Views/Categorias/Details.cshtml
@model Gestor.Models.Categoria

@{
    ViewBag.Title = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes</h2>

<div>
    <h4>Categoria</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Apelido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apelido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Alterar", "Edit", new { id = Model.CategoriaId }) |
    @Html.ActionLink("Retornar a lista", "Index")
</p>

Gestor/Views/Categorias/Edit.cshtml
@model Gestor.Models.Categoria

@{
    ViewBag.Title = "Alterar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Alterar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Categoria</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CategoriaId)

        <div class="form-group">
            @Html.LabelFor(model => model.Apelido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apelido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apelido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input class="btn btn-sm" type="submit" value="Gravar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retornar a lista", "Index")
</div>

Gestor/Views/Categorias/Erase.cshtml
@model Gestor.Models.Categoria
@{
    ViewBag.Title = "Confirmar Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Confirmar Eliminar</h2>
<h3>CONFIRME que realmente deseja eliminar o registro?</h3>
@Html.Partial("Common")
@using (Html.BeginForm("Erase", "Categorias", new { Id = Model.CategoriaId }))
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input class="btn btn-sm" type="submit" value="Eliminar" class="btn btn-primary" /> |
        @Html.ActionLink("Retornar a lista sem eliminar", "Index")
    </div>
}

Gestor/Views/Categorias/Index.cshtml
@model IEnumerable<Gestor.Models.Categoria>
@using X.PagedList.Mvc;
@using X.PagedList;
@{
    ViewBag.Title = "Índice";
    Layout = "~/Views/Shared/_Layout.cshtml";
    IPagedList<Gestor.Models.Categoria> categorias = ViewBag.OnePageHistory;
}
<h2>Índice</h2>
<p>
    @Html.ActionLink("Criar nova categoria", "Create")
</p>
@using (Html.BeginForm("Search", "Categorias", FormMethod.Post))
{
    <p>
        Código: @Html.TextBox("search")
        <input class="btn btn-sm" type="submit" value="Procurar" />
    </p>
}
<div class="height600">
    <table class="table fancyTable">
        <thead>
            <tr>
                <th></th>
                <th>
                    @Html.DisplayNameFor(model => model.Apelido)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Descricao)
                </th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in categorias)
            {
                <tr>
                    <td>
                        @Html.ActionLink("Alterar", "Edit", new { id = item.CategoriaId }) <br />
                        @Html.ActionLink("Detalhes", "Details", new { id = item.CategoriaId }) <br />
                        @Html.ActionLink("Eliminar", "Delete", new { id = item.CategoriaId })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Apelido)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descricao)
                    </td>
                    <td>
                        @Html.ActionLink("Alterar", "Edit", new { id = item.CategoriaId }) <br />
                        @Html.ActionLink("Detalhes", "Details", new { id = item.CategoriaId }) <br />
                        @Html.ActionLink("Eliminar", "Delete", new { id = item.CategoriaId })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@Html.PagedListPager((IPagedList)ViewBag.OnePageHistory, page => Url.Action("Index", new { page }))

@section scripts {
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery.fixedheadertable.min.js"></script>

    <script type="text/javascript">

        $('.table').fixedHeaderTable({
            footer: true,
            cloneHeadToFoot: false,
            altClass: 'odd',
            autoShow: true
        });

    </script>

}